config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  resources :projects
  resources :artists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_and_belongs_to_many :projects

    def to_s
        pseudo
    end
end

app/models/project.rb
class Project < ApplicationRecord
    has_and_belongs_to_many :artists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[ show edit update destroy ]

  # GET /artists or /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1 or /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists or /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: "Artist was successfully created." }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1 or /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: "Artist was successfully updated." }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1 or /artists/1.json
  def destroy
    @artist.destroy!

    respond_to do |format|
      format.html { redirect_to artists_path, status: :see_other, notice: "Artist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.expect(artist: [ :pseudo, :image, :description ])
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # Récupérer tous les projets triés par date de manière décroissante
    @projects = Project.all.order(date: :asc)

    # Regrouper les projets par date
    @projects_by_date = @projects.group_by(&:date)
  end

  def show
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.expect(project: [ :name, :cover, :date, :tracklist, artist_ids: [] ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/artists/_artist.html.erb
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body text-center">
                        <h2 class="card-title"><%= artist.pseudo %></h2>
                        <img src="<%= artist.image %>" alt="<%= artist.pseudo %>" class="img-fluid mb-3">
                        <p><strong>Description:</strong> <%= artist.description %></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

app/views/artists/_form.html.erb
<%= simple_form_for(@artist) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :pseudo %>
    <%= f.input :image %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<% content_for :title, "Editing artist" %>

<h1>Editing artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Show this artist", @artist %> |
  <%= link_to "Back to artists", artists_path %>
</div>

app/views/artists/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Artists" %>

<h1>Artists</h1>

<div id="artists">
  <% @artists.each do |artist| %>
    <%= render artist %>
    <p>
      <%= link_to "Show this artist", artist %>
    </p>
  <% end %>
</div>

<%= link_to "New artist", new_artist_path %>

app/views/artists/new.html.erb
<% content_for :title, "New artist" %>

<h1>New artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Back to artists", artists_path %>
</div>

app/views/artists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artist %>

<div>
  <%= link_to "Edit this artist", edit_artist_path(@artist) %> |
  <%= link_to "Back to artists", artists_path %>

  <%= button_to "Destroy this artist", @artist, method: :delete %>
</div>

app/views/home/index.html.erb
<body>
   
  
    <div class="titles">
        <h1 style="font-size: 1000%;">RAP CLOCK</h1>
        <div class="clock-container">
            <%= image_tag "clock.png" , class: "clock" %>
        </div>

    </div>
    <div class="flex">
      <span id="countdown" class="timer">Test</span>
    </div>
    <div class="container">
        <div class="row">
            <% @projects_by_date.each do |date, projects| %>
            <div class="col-12">
                <h2>
                <% if date == Date.today %>
                    <div class="row">
                        <div class="col-12 text-center">
                        <h2>Aujourd'hui</h2>
                        </div>
                    </div>
                    
                <% elsif date == Date.tomorrow %>
                    <div class="row">
                        <div class="col-12 text-center">
                        <h1>Demain</h1>
                        </div>
                    </div>
                    
                <% else %>
                    <%= date.strftime("%d %B %Y") %> 
                <% end %>
                </h2>
            </div>

            <% projects.each do |project| %>
                <div class="col-md-3">
                <%= link_to project_path(project), id: dom_id(project) do %> <!-- Lien vers la page show du projet -->                     
                    <div class="box">
                        <img src="<%= project.cover %>" alt="<%= project.name %>" class="img-fluid">
                        <h3><%= project.name %></h3>
                        <h6>
                            <% if project.artists.any? %>
                            <%= project.artists.map(&:pseudo).join(", ") %>
                            <% else %>
                            Pas d'artistes.
                            <% end %>
                        </h6>
                    </div>

                <% end %>
                </div>
            <% end %>
            <% end %>
        </div>
    </div>
    <script>
  function getNextFridayMidnight() {
      const now = new Date();
      let nextFriday = new Date(now);
      nextFriday.setDate(now.getDate() + ((5 - now.getDay() + 7) % 7 || 7)); // Prochain vendredi
      nextFriday.setHours(0, 0, 0, 0);
      return nextFriday;
  }

  function updateCountdown() {
      const now = new Date();
      const targetDate = getNextFridayMidnight();
      const diff = targetDate - now;
      
      if (diff <= 0) {
          document.getElementById("countdown").textContent = "00 00 00 00";
          return;
      }
      
      const days = Math.floor(diff / (1000 * 60 * 60 * 24));
      const hours = Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
      const seconds = Math.floor((diff % (1000 * 60)) / 1000);
      
      document.getElementById("countdown").textContent = 
          `${days.toString().padStart(1, '')} j ${hours.toString().padStart(2, '')} h ${minutes.toString().padStart(2, '0')} m ${seconds.toString().padStart(2, '0')} s `;
  }

  setInterval(updateCountdown, 1000);
  document.addEventListener("DOMContentLoaded", updateCountdown);
  
</script>

  </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rap Clock 4" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    
    <%= javascript_importmap_tags %>
  </head>
<style>
    @font-face {
      font-family: 'Neue Plak Thin';
      src: url('/assets/Neue Plak Thin.ttf') format('truetype');
      font-weight: normal;
      font-style: normal;
    }

    body {
        font-family: 'Neue Plak Thin', sans-serif;
    }
    a {
        text-decoration: none; /* Supprime le soulignement */
        color: inherit; /* Prend la couleur du texte parent (ici celle de votre titre ou du projet) */
    }
    .box {
        height: auto ;
        width: auto ;
        margin-bottom: 105px;
        justify-content: center;
        
    }

    .img-fluid {
        border-radius: 20px;
    }
    .titles {
        display: flex;
        flex-direction: column;
        align-items: center; /* Centre le contenu */
    }
    .clock-container {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 100%;
    }
    .clock {
        width: 400px; /* Ajuste la largeur */
        height: auto; /* Garde les proportions */
        bottom: 60px;
        position:relative;

    }
    .navbar {
        padding: 15px 0;
        border-bottom: 1px solid #e9ecef;
    }
    header .navbar .navbar-brand {
        background-color: #2279cf;
    }
    .navbar-brand img {
        max-height: 50px;
    }

    .navbar-nav .nav-link {
        font-size: 1.2rem;
        margin-left: 15px;
    }
    .navbar-light .navbar-nav .nav-link {
        color: rgb(0, 0, 0);
    }

</style>
  <body>
      <header style="background-color: #ffffff !important" class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <!-- Logo + Nom -->
            <a class="navbar-brand d-flex align-items-center" href="<%= root_path %>">
                <%= image_tag "clock.png" %>
                <span style="font-weight: bold; font-size: 1.5rem;">RAP CLOCK</span>
            </a>

            <!-- Bouton pour mobile -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <!-- Liens à droite -->
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <%= link_to "Artistes", artists_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Projets", projects_path, class: "nav-link" %>
                    </li>
                </ul>
            </div>
        </div>
      </header>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :cover %>
    <%= f.input :date %>
    <%= f.input :tracklist %>
    <%= f.association :artists,
                      prompt: "Sélectionner des artistes" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body text-center">
                        <h2 class="card-title"><%= project.name %></h2>
                        <img src="<%= project.cover %>" alt="<%= project.name %>" class="img-fluid mb-3">
                        <p><strong>Date:</strong> <%= project.date %></p>
                        <p><strong>Tracklist:</strong> <%= project.tracklist %></p>
                        <p><strong>Artists:</strong></p>
                        <% if project.artists.any? %>
                            <ul class="list-group">
                                <% project.artists.each do |artist| %>
                                    <li class="list-group-item"><%= artist.pseudo %></li>
                                <% end %>
                            </ul>
                        <% else %>
                            <p>Pas d'artistes.</p>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Projects" %>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>